# Site settings
title: Mohammed Pivezhani's Academic Site
email: mohammad.pivezhani@example.com
description: >-
  Assistant Professor at [Your University]. Research interests include [your field].
  This site contains my publications, teaching, and contact information.
baseurl: ""
url: "https://pivezhan.github.io"
twitter_username: yourtwitterhandle
github_username: pivezhan

# Add navigation links for the header
header_pages:
  - publications.md
  - news.md
  - teaching.md
  - cv.md
  - projects.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/