# Site settings
title: Mohammed Pivezhani
email: pivezhandi@wayne.edu
description: >-
  PhD candidate at Wayne State University, Department of Computer Science.
  Research focuses on data-efficient AI-guided energy- and thermal-aware scheduling
  for heterogeneous multicore systems in the Embedded Systems Lab. Experienced in
  high-performance computing, reinforcement learning, and computer architecture.
baseurl: ""
url: "https://pivezhan.github.io"
twitter_username: pivezhandi
github_username: pivezhan

# Add navigation links for the header
header_pages:
  - index.markdown
  - publications.md
  - news.md
  - teaching.md
  - cv.md
  - projects.md

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/